name: Release

on:
  workflow_dispatch:
    inputs:
      strategy:
        description: "Valid semver (x.x.x) or strategy (patch, minor, major)"
        default: "patch"
        required: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'pebie' || github.actor == 'leguellec' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --immutable-cache

      - name: Build the project
        run: yarn build

      - name: Bump version
        id: versioning
        run: |
          yarn version ${{ github.event.inputs.strategy }}
          VERSION=$(node -p "require('./package.json').version")
          echo "current-version=$VERSION" >> $GITHUB_OUTPUT

      - name: Commit and tag release
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "chore(release): v${{ steps.versioning.outputs.current-version }}"
          git tag v${{ steps.versioning.outputs.current-version }}
          git push --follow-tags

      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v2

      - name: Run git-cliff to generate changelog
        id: changelog
        run: |
          git-cliff --latest > temp_changelog
          cat temp_changelog CHANGELOG.md > temp && mv temp CHANGELOG.md
          echo "changelog-body<<EOF" >> $GITHUB_OUTPUT
          cat temp_changelog >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Log changes
        run: |
          echo "The changelog will be: $(git cliff --latest)"

      - name: Commit changelog
        run: |
          git add CHANGELOG.md
          git commit -m "docs: update changelog for v${{ steps.versioning.outputs.current-version }}"
          git push

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.changelog-body}}
          tag_name: v${{ steps.versioning.outputs.current-version }}
          name: v${{ steps.versioning.outputs.current-version }}

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}